### ISSUE TITLE
可以考虑搭个公共的 slide 平台

### ISSUE THREAD

**Issue by welefen** [akira-cn/matrix#1]

**Comment by duojin** [comment]
npm install 时发生错误

46588 warn optional Skipping failed optional dependency /chokidar/fsevents:
46589 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
46590 warn thinkjs-application@1.0.0 No repository field.
46591 warn thinkjs-application@1.0.0 No license field.
46592 verbose stack Error: sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
46592 verbose stack Exit status 1
46592 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
46592 verbose stack     at emitTwo (events.js:106:13)
46592 verbose stack     at EventEmitter.emit (events.js:191:7)
46592 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
46592 verbose stack     at emitTwo (events.js:106:13)
46592 verbose stack     at ChildProcess.emit (events.js:191:7)
46592 verbose stack     at maybeClose (internal/child_process.js:850:16)
46592 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
46593 verbose pkgid sqlite3@3.1.4
46594 verbose cwd E:\githubRepsitory\matrix
46595 error Windows_NT 6.1.7601
46596 error argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
46597 error node v6.2.0
46598 error npm  v3.8.9
46599 error code ELIFECYCLE
46600 error sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
46600 error Exit status 1
46601 error Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
46601 error Make sure you have the latest version of node.js and npm installed.
46601 error If you do, this is most likely a problem with the sqlite3 package,
46601 error not with npm itself.
46601 error Tell the author that this fails on your system:
46601 error     node-pre-gyp install --fallback-to-build
46601 error You can get information on how to open an issue for this project with:
46601 error     npm bugs sqlite3
46601 error Or if that isn't available, you can get their info via:
46601 error     npm owner ls sqlite3
46601 error There is likely additional logging output above.
46602 verbose exit [ 1, true ]
